version: '3'
  
includes:
  snapi:
    taskfile: ../../Taskfile.yml
    dir: ../..

tasks:
  run:
    desc: Run the generator
    cmds:
      - task: snapi:build-snapi-pkg-image
      - cmd: >
          docker run -it --rm -v $(pwd):/app snapi
          python gen.py
